name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Add GitHub Packages source
      run: dotnet nuget add source --username orskovacs --password ${{ secrets.GH_PACKAGES_PAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/orskovacs/index.json"

    - run: dotnet workload restore
      working-directory: dot-net-gateway

    - run: dotnet build
      working-directory: dot-net-gateway

    - name: Publish dotnet WASM project
      run: dotnet publish
      working-directory: dot-net-gateway

    - name: Build static assets using Node
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'npm'
    - run: npm ci
      working-directory: client
    - run: npm run build
      working-directory: client

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        name: github-pages
        path: client/dist/

  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      permissions:
        pages: write
        id-token: write
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
